<a href="https://colab.research.google.com/github/patilyogita7/Artificial_Intelligence_Lab_SE_A_45/blob/master/Practical_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr= ([[2,1,4],
       [1,2,5],
       [2,3,6]])
print(arr[0][ 0]*((arr[1][1]*arr[2][2])-(arr[1][2]*arr[2][1]))-arr[0][1]*((arr[1][0]*arr[2][2])-(arr[1][2]*arr[2][0]))+arr[0][2]*((arr[1][0]*arr[2][1])-(arr[1][1]*arr[2][0])))

-6


In [3]:
# Inverse of 3x3 matrix without numpy

def determinant(m):
  return (
m[0][0]*(m[1][1]*m[2][2] - m[1][2]*m[2][1])
- m[0][1]*(m[1][0]*m[2][2] - m[1][2]*m[2][0])
+ m[0][2]*(m[1][0]*m[2][1] - m[1][1]*m[2][0])
)

def inverse_3x3(m):
    det = determinant(m)

    if det == 0:
        print("Matrix has no inverse")
        return None

    # Cofactor matrix
    cof = [
        [
            (m[1][1]*m[2][2] - m[1][2]*m[2][1]),
            -(m[1][0]*m[2][2] - m[1][2]*m[2][0]),
            (m[1][0]*m[2][1] - m[1][1]*m[2][0])
        ],
        [
            -(m[0][1]*m[2][2] - m[0][2]*m[2][1]),
            (m[0][0]*m[2][2] - m[0][2]*m[2][0]),
            -(m[0][0]*m[2][1] - m[0][1]*m[2][0])
        ],
        [
            (m[0][1]*m[1][2] - m[0][2]*m[1][1]),
            -(m[0][0]*m[1][2] - m[0][2]*m[1][0]),
            (m[0][0]*m[1][1] - m[0][1]*m[1][0])
        ]
    ]

    # Transpose of cofactor (adjoint)
    adj = [[cof[j][i] for j in range(3)] for i in range(3)]

    # Divide by determinant
    inv = [[adj[i][j]/det for j in range(3)] for i in range(3)]
    return inv

# Example matrix

matrix = [
[1, 2, 3],
[0, 1, 4],
[5, 6, 0]
]

result = inverse_3x3(matrix)

print("Inverse matrix:")
for row in result:
    print(row)

Inverse matrix:
[-24.0, 18.0, 5.0]
[20.0, -15.0, -4.0]
[-5.0, 4.0, 1.0]


In [5]:
import numpy as np

# Create a 3x3 matrix
matrix_np = np.array([
    [1, 2, 3],
    [0, 1, 4],
    [5, 6, 0]
])

print("Original 3x3 matrix:")
print(matrix_np)

# Compute the determinant
determinant_np = np.linalg.det(matrix_np)

print(f"\nDeterminant of the matrix: {determinant_np}")

Original 3x3 matrix:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Determinant of the matrix: 0.9999999999999964


In [6]:
# Compute the inverse of the matrix
inverse_matrix_np = np.linalg.inv(matrix_np)

print("\nInverse of the matrix:")
print(inverse_matrix_np)


Inverse of the matrix:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


In [8]:
import numpy as np

# Define the coefficient matrix A
A = np.array([
    [2, 3],
    [4, 5]
])

# Define the constant vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
print(A)
print("\nConstant Vector B:")
print(B)

# Solve the system of linear equations Ax = B
x = np.linalg.solve(A, B)

print("\nSolution (x, y):")
print(x)


Coefficient Matrix A:
[[2 3]
 [4 5]]

Constant Vector B:
[10 20]

Solution (x, y):
[5. 0.]
